[tool.poetry]
name = "SlotContrast"
version = "0.1.0"
description = "Temporally Consistent Object-Centric Learning by Contrasting Slots"
authors = [
  "Anna Manasyan",
  "Andrii Zadaianchuk"
]
readme = "README.md"
